/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\EulerAngles.cpp
 *  model: Controller
 *  expmt: JIWY-TheoreticalModel
 *  date:  July 1, 2021
 *  time:  2:55:59 PM
 *  user:  20-sim 4.8 Campus License
 *  from:  Universiteit Twente
 *  build: 4.8.3.10415
 **********************************************************/

/*****************************************************************************
--------------------------------------------------------------------------

 Copyright � 1995-2007 Controllab Products B.V. All Rights Reserved.

             www.controllab.nl
               www.20sim.com

 Authors: Frank Groen
--------------------------------------------------------------------------
 Description:

 Contains code for converting between different angle representations
 all 24 different kind of Euler angles
 Quaternions and H-Matrices and Rotation Matrices
--------------------------------------------------------------------------
******************************************************************************/

