/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.h
 *  model: Controller
 *  expmt: JIWY-TheoreticalModel
 *  date:  July 1, 2021
 *  time:  2:55:59 PM
 *  user:  20-sim 4.8 Campus License
 *  from:  Universiteit Twente
 *  build: 4.8.3.10415
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
